driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y which initscripts
  run_list:
    - recipe[mysql_test::yum_repo]
      
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts
  run_list:
    - recipe[mysql_test::yum_repo]
      
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install net-tools lsof
  run_list:
    - recipe[mysql_test::yum_repo]

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which
  run_list:
    - recipe[mysql_test::yum_repo]

# FIXME: debian-7 multi is broken for some reason
# - name: debian-7
#   driver:
#     image: debian:7
#     intermediate_instructions:
#       - RUN /usr/bin/apt-get update
#       - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd

- name: opensuse-42.1
  driver:
    image: opensuse:42.1
    pid_one_command: /bin/systemd

suites:
  #
  # client
  #
  - name: installation_client_package-50
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.0'
    includes: [
      'centos-5'
    ]

  - name: installation_client_package-51
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.1'
    includes: [
      'centos-5',
      'centos-6'
    ]

  - name: installation_client_package-55
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.5'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'debian-7',
      'debian-8',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: installation_client_package-56
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.6'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-42.1'
    ]

  - name: installation_client_package-57
    run_list:
    - recipe[mysql_test::installation_client]
    attributes:
      mysql:
       version: '5.7'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-16.04'
    ]

  #
  # server
  #
  - name: installation_server_package-50
    run_list:
    - recipe[mysql_test::installation_server]
    attributes:
      mysql:
       version: '5.0'
    includes: [
      'centos-5'
    ]

  - name: installation_server_package-51
    run_list:
    - recipe[mysql_test::installation_server]
    attributes:
      mysql:
       version: '5.1'
    includes: [
      'centos-5',
      'centos-6'
    ]

  - name: installation_server_package-55
    run_list:
    - recipe[mysql_test::installation_server]
    attributes:
      mysql:
       version: '5.5'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'debian-7',
      'debian-8',
      'ubuntu-12.04',
      'ubuntu-14.04'
    ]

  - name: installation_server_package-56
    run_list:
    - recipe[mysql_test::installation_server]
    attributes:
      mysql:
       version: '5.6'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-42.1'
    ]

  - name: installation_server_package-57
    run_list:
    - recipe[mysql_test::installation_server]
    attributes:
      mysql:
       version: '5.7'
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-16.04'
    ]

  #
  # service
  #

  # singles
  
  - name: service50-single
    run_list:
    - recipe[mysql_test::service_single]
    includes: [
      'centos-5'
     ]
    attributes:
      mysql:
       version: '5.0'

  - name: service51-single
    run_list:
    - recipe[mysql_test::service_single]
    includes: [
      'centos-5',
      'centos-6'
     ]
    attributes:
      mysql:
       version: '5.1'

  - name: service55-single
    run_list:
    - recipe[mysql_test::service_single]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'debian-7',
      'debian-8',
      'ubuntu-12.04',
      'ubuntu-14.04'
     ]
    attributes:
      mysql:
       version: '5.5'

  - name: service56-single
    run_list:
    - recipe[mysql_test::service_single]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-42.1'
     ]
    attributes:
      mysql:
       version: '5.6'

  - name: service57-single
    run_list:
    - recipe[mysql_test::service_single]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-16.04'
     ]
    attributes:
      mysql:
       version: '5.7'

  # multi
       
  - name: service50-multi
    run_list:
    - recipe[mysql_test::service_multi]
    includes: [
      'centos-5'
     ]
    attributes:
      mysql:
       version: '5.0'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       run_group: 'bob'
       initial_root_password: 'string with spaces'

  - name: service51-multi
    run_list:
    - recipe[mysql_test::service_multi]
    includes: [
      'centos-5'
     ]
    attributes:
      mysql:
       version: '5.1'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       run_group: 'bob'
       initial_root_password: 'string with spaces'

  - name: service55-multi
    run_list:
    - recipe[mysql_test::service_multi]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'debian-7',
      'debian-8',
      'ubuntu-12.04',
      'ubuntu-14.04'
     ]
    attributes:
      mysql:
       version: '5.5'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       run_group: 'bob'
       initial_root_password: 'string with spaces'

  - name: service56-multi
    run_list:
    - recipe[mysql_test::service_multi]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-42.1'
     ]
    attributes:
      mysql:
       version: '5.6'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       run_group: 'bob'
       initial_root_password: 'string with spaces'

  - name: service57-multi
    run_list:
    - recipe[mysql_test::service_multi]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-16.04'
     ]
    attributes:
      mysql:
       version: '5.7'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       run_group: 'bob'
       initial_root_password: 'string with spaces'
  #
  # config
  #
  - name: config50
    run_list:
    - recipe[mysql_test::config]
    includes: [
      'centos-5'
     ]
    attributes:
      mysql:
       version: '5.0'

  - name: config51
    run_list:
    - recipe[mysql_test::config]
    includes: [
      'centos-5'
     ]
    attributes:
      mysql:
       version: '5.1'

  - name: config55
    run_list:
    - recipe[mysql_test::config]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'debian-7',
      'debian-8',
      'ubuntu-12.04',
      'ubuntu-14.04'
     ]
    attributes:
      mysql:
       version: '5.5'

  - name: config56
    run_list:
    - recipe[mysql_test::config]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'ubuntu-14.04',
      'opensuse-13.2',
      'opensuse-42.1'
     ]
    attributes:
      mysql:
       version: '5.6'

  - name: config57
    run_list:
    - recipe[mysql_test::config]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'redhat-6',
      'redhat-7',
      'fedora-latest',
      'ubuntu-16.04'
     ]
    attributes:
      mysql:
       version: '5.7'

  #
  # smoke
  #
  - name: smoke
    run_list:
    - recipe[mysql_test::smoke]
    includes: [
      'centos-5',
      'centos-6',
      'centos-7',
      'fedora-latest',
      'debian-7',
      'debian-8',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'fedora-latest',
      'opensuse-13.2',
      'opensuse-42.1'
     ]
